### ISSUE TITLE
Allow experimenter to configure API details in the front-end (without modifying config file)

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/deliberate-lab#100]
This should carry over across experiments - perhaps an "API key" field (or API key per supported language model) in Settings?

Also add validation upon adding an "LLM Mediator" during the chat component in case the experimenter tries to add a mediator without having already added their key - e.g. "You don't have a Gemini 3.5 API key listed! Please do so in Settings."

**Comment by vivtsai** [comment]
Fixed by refactor
