### ISSUE TITLE
Mediator appears to double-post

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/deliberate-lab#101]
![Image](https://github.com/PAIR-code/llm-mediation-experiments/assets/4844633/d50bec10-790c-4331-ad31-d3ed0a77aa46)

**Comment by vivtsai** [comment]
NOTE: Let's double-check, but I have a hunch this is because the LLM response to both participants A and B are the same (e.g., participant A posts, LLM response A loading, participant B posts, LLM response B loading... but since posting messages takes a while, both responses A and B post).
