### ISSUE TITLE
Update survey reveal params - add a checkbox for "reveal all participants" (as opposed to just one participant)

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/deliberate-lab#230]

**Comment by vivtsai** [comment]
By this, do you mean add the option to configure it in the stage configuration (during experiment creation)? It should be present for LAS right now

**Comment by cjqian** [comment]
Yes, option to configure it during experiment creation! (If it's not too hard to add, it'd also be nice to have an "all participants" option)
