### ISSUE TITLE
For synchronous stages (chat, election), don't allow participants to move forward until N participants have hit the stage (add this stage parameter, and remove it from experiment parameters)

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/deliberate-lab#233]

**Comment by vivtsai** [comment]
We now have `minParticipants`, which prevents everyone from **starting** (not completing) the stage if min participants is not reached. Is that acceptable?

I think it's okay to keep the experimenter param one—that prevents people from clicking "Start experiment" (which is before any of the stages). We might never use it but it's not actually redundant
