### ISSUE TITLE
Make info icon easier to read

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/deliberate-lab#260]
![Image](https://github.com/user-attachments/assets/b2c2ab7c-7c02-43be-8e06-5ca481cd2e8b)

**Comment by vivtsai** [comment]
Let's do this for "help" icon too! (Maybe similar to what you had in the original - sorry that I didn't have time to bring that over.)

We'll also want a max height (maybe `calc(100vh - common.$header-height * 2)`?) with overflow auto.
