### ISSUE TITLE
Bug: duplicated notice on whose turn it is to make a bid for the first bid

### ISSUE THREAD

**Issue by cjqian** [PAIR-code/deliberate-lab#366]
https://cjq-dot-deliberate-lab.appspot.com/#/e/23c877c9-9b48-4669-9970-745a4faac33a/p/deadbdd9-d32a-434d-a935-349f8e9b39d3/negotiation1

**Comment by vivtsai** [comment]
I think this has been fixed. Let's test after re-deploying.
