### ISSUE TITLE
Enable chat history / mediation message options for LLM calls

### ISSUE THREAD

**Issue by vivtsai** [PAIR-code/deliberate-lab#85]
We have two fields in the backend that aren't currently configurable (i.e., implemented) in frontend:

- chat history: in LLM call, use entire chat history, only current LAS discussion, or only last message
- filter mediation messages: in LLM when taking chat history, filter vs. don't filter out mediation messages

**Comment by cjqian** [comment]
Do we actually need configurability here? On more thought, this might be overengineering - a human:agent analog seems reasonable to me; humans see all of the names and can view the whole conversation; so should the agents. In the future when there is an API, agent developers can obfuscate this information if needed. There aren't any requests for this currently (and the Gemini context window is quite large).

I'll go ahead and close this. If you think of any reasons why this should be prioritized, please feel free to re-open!
